name: Firebase Test with Emulator

on:
  push:
    branches:
      - feature/firebase-test-harness
      - main
      - feature/dim-label-fix
  pull_request:
    branches:
      - main

jobs:
  test-with-emulator:
    runs-on: ubuntu-latest
    
    env:
      USE_FIREBASE_EMULATOR: 1
      FIREBASE_EMULATOR_HOST: localhost
      FIRESTORE_EMULATOR_HOST: localhost:8080
      FIREBASE_AUTH_EMULATOR_HOST: localhost:9099
      FIREBASE_STORAGE_EMULATOR_HOST: localhost:9199
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Start Firebase Emulators
        run: |
          firebase emulators:start --only auth,firestore,storage --project demo-test &
          sleep 10
      
      - name: Run Firebase Integration Tests
        run: |
          npm run test -- --run src/firebase/__tests__/*.integration.test.ts
        continue-on-error: true
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: firebase-test-results
          path: |
            coverage/
            test-results/
      
      - name: Comment PR with Results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const testResults = '🔵 Firebase Emulator Tests Complete';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: testResults
            });